"""empty message

Revision ID: 13d6f7bc9982
Revises: 
Create Date: 2019-05-18 02:50:35.624790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d6f7bc9982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('family_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('locale', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('given_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('verified_email', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_given_name'), 'user', ['given_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_given_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
