"""empty message

Revision ID: 77112f7b5e24
Revises: 
Create Date: 2019-05-21 11:47:06.816026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77112f7b5e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('family_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('locale', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('given_name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('verified_email', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_given_name'), 'user', ['given_name'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_index(op.f('ix_user_given_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
